image: node:10.14.0

cache:
  paths:
    - node_modules/
  
jest:
  stage: test
  script: 
    - npm install -g knex
    - npm install
    - knex migrate:latest --env test
    - knex seed:run --env test
    - npm test
  only:
    - master

# production:
#   type: deploy
#   stage: deploy
#   image: ruby:latest
#   script:
#     - apt-get update -qy
#     - apt-get install -y ruby-dev
#     - gem install dpl
#     - dpl --provider=heroku --app=api-lavrata-staging --api-key=$HEROKU_API_KEY
#   only:
#     - master